services:

  # -------------------------------------
  # SQL Server
  # -------------------------------------
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "moneybeeadmin123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - moneybee-network

  # -------------------------------------
  # Redis
  # -------------------------------------
  redis:
    image: redis:7
    container_name: moneybee-redis
    ports:
      - "6379:6379"
    networks:
      - moneybee-network

  # -------------------------------------
  # Internal APIs
  # -------------------------------------
  auth-api:
    build:
      context: .
      dockerfile: ./src/Auth/MoneyBee.Auth.Api/Dockerfile
    depends_on:
      - sqlserver
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sqlserver,1433;Database=MoneyBee_Auth;User Id=sa;Password=moneybeeadmin123!;TrustServerCertificate=True
      - Redis__Connection=redis:6379
    ports:
      - "5001:8080"
    networks:
      - moneybee-network

  customer-api:
    build:
      context: .
      dockerfile: ./src/Customer/MoneyBee.Customer.Api/Dockerfile
    depends_on:
      - sqlserver
      - redis
      - kyc-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sqlserver,1433;Database=MoneyBee_Customer;User Id=sa;Password=moneybeeadmin123!;TrustServerCertificate=True
      - Redis__Connection=redis:6379
      - KycService__Url=http://kyc-service:80
    ports:
      - "5002:8080"
    networks:
      - moneybee-network

  transfer-api:
    build:
      context: .
      dockerfile: ./src/Transfer/MoneyBee.Transfer.Api/Dockerfile
    depends_on:
      - sqlserver
      - redis
      - customer-api
      - fraud-service
      - exchange-rate
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sqlserver,1433;Database=MoneyBee_Transfer;User Id=sa;Password=moneybeeadmin123!;TrustServerCertificate=True
      - Redis__Connection=redis:6379
      - CustomerApi__Url=http://customer-api:8080
      - FraudApi__Url=http://fraud-service:8080
      - ExchangeRateService__Url=http://exchange-rate:80
    ports:
      - "5003:8080"
    networks:
      - moneybee-network

  # -------------------------------------
  # External Services
  # -------------------------------------
  fraud-service:
    image: bpnpay/fraud-service:latest
    container_name: fraud-service
    ports:
      - "8081:8081"
    networks:
      - moneybee-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 20s
      timeout: 10s
      retries: 3

  kyc-service:
    image: bpnpay/kyc-service:latest
    container_name: kyc-service
    ports:
      - "8082:8082"
    networks:
      - moneybee-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 20s
      timeout: 10s
      retries: 3

  exchange-rate:
    image: bpnpay/exchange-rate-service:latest
    container_name: exchange-rate
    ports:
      - "8083:8083"
    networks:
      - moneybee-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 20s
      timeout: 10s
      retries: 3

# -------------------------------------
# Volumes
# -------------------------------------
volumes:
  sql_data:

# -------------------------------------
# Network
# -------------------------------------
networks:
  moneybee-network:
    driver: bridge
